### ISSUE TITLE
v0.37.5 버전에서 undefined에서 rectangle을 못찾는다는 에러가 발생하네요

### ISSUE THREAD

**Issue by andyleeboo** [uprise-fin/heybit-ui-styled-components#90]
heybit-harvest-www 프로젝트에서 husc 버전을 0.35.7에서 0.37.5로 업그레이드 했습니다.

버전 업을 했더니 아래와 같은 에러가 발생하고 있습니다. 

혹시 known issue인지, 하베스트에서만 발생하는건지 몰라 이슈 올립니다. 
husc 버전 업 하기 전에 sveltekit 1.x, vite 4.x 버전으로 업데이트 했습니다.

```
Cannot read properties of undefined (reading 'rectangle')
TypeError: Cannot read properties of undefined (reading 'rectangle')
    at HeaderFooterLayout.svelte:70:27
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/routes/+layout.svelte:15:106)
    at Object.$$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at root.svelte:40:37
    at $$render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1876:22)
    at Object.render (/node_modules/.pnpm/svelte@3.55.0/node_modules/svelte/internal/index.mjs:1884:26)
    at render_response (file:///Users/hoho/Developer/uprise/heybit-harvest-www/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.4/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:105:27)
    at async render_page (file:///Users/hoho/Developer/uprise/heybit-harvest-www/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.4/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:299:10)
    at async resolve (file:///Users/hoho/Developer/uprise/heybit-harvest-www/node_modules/.pnpm/@sveltejs+kit@1.0.1_svelte@3.55.0+vite@4.0.4/node_modules/@sveltejs/kit/src/runtime/server/index.js:356:17)
```

**Comment by andyleeboo** [comment]
husc v0.36.0 버전에서는 해당 에러가 발생하지 않습니다.

**Comment by heybitSky** [comment]
> husc v0.36.0 버전에서는 해당 에러가 발생하지 않습니다.

확인해볼게요

**Comment by heybitSky** [comment]
> 네 저도 정확히 몇버전에서 break 하는지 파악해서 알려드릴게요.

37버전을 사용하려면 타입을 대대적(?)으로 수정해야 합니다.
